experimental: Testing the unification of processes in pipelines

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -8,6 +8,33 @@
 
 definitions:
   steps:
+    - step: &git-police
+        name: Git Police Step
+        script:
+          - printenv
+          - echo "-------------------------------------------------------------------------"
+          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+          - docker run -d -p 5000:5000 -e REPO_TOKEN="${ETENDOBOT_TOKEN}" -e PR_ID="$BITBUCKET_PR_ID" -e REPO_NAME="$BITBUCKET_REPO_SLUG" etendo/gitpolice:"${GITPOLICE_VERSION}"
+          - echo "-------------------------------------------------------------------------"
+          - sleep 10s
+          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/api/bitbucket)
+          - |
+            if [ "$response" -ne 200 ]; then
+              echo "API call failed with status code $response"
+              cat response.txt
+              exit 1
+            fi
+          - |
+            if ! grep -q "Valid branch name and correct destination" response.txt; then
+              echo "Git Police check failed: response does not contain 'Valid branch name and correct destination'"
+              echo "Full response:"
+              cat response.txt
+              exit 1
+            fi
+          - echo "API call successful with status code $response"
+          - cat response.txt
+        services:
+          - docker
     - step: &build-step
         image: maven:3.3.9
         name: SonarQube analysis
@@ -20,11 +47,11 @@ definitions:
         name: Make Review Step
         script:
           - printenv
-          - echo "-------------------------------------------------------------------------"
-          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:latest
-          - echo "-------------------------------------------------------------------------"
-          - sleep 10s
+          -  echo "-------------------------------------------------------------------------"
+          -  echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+          -  docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:${REVIEWER_VERSION}
+          -  echo "-------------------------------------------------------------------------"
+          -  sleep 10s
           - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
           - if [ $response -ne 200 ]; then
           - echo "API call failed with status code $response"
@@ -37,6 +64,39 @@ definitions:
           - cat response.txt
         services:
           - docker
+    - &build-push-amd64
+      name: Build and Push for amd64
+      script:
+        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - IMAGE=etendo/etendo_copilot_core:${BRANCH_NAME}-amd64
+        - docker build --platform linux/amd64 -t ${IMAGE} .
+        - docker push ${IMAGE}
+      services:
+        - docker
+    - &build-push-arm64
+      name: Build and Push for arm64
+      runs-on:
+        - self.hosted
+        - linux.arm64
+      script:
+        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - IMAGE=etendo/etendo_copilot_core:${BRANCH_NAME}-arm64
+        - docker build --platform linux/arm64/v8 -t ${IMAGE} .
+        - docker push ${IMAGE}
+      services:
+        - docker
+    - &create-push-manifest
+      name: Create and Push Manifest
+      script:
+        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+        - docker pull etendo/etendo_copilot_core:${BRANCH_NAME}-amd64
+        - docker pull etendo/etendo_copilot_core:${BRANCH_NAME}-arm64
+        - docker manifest create etendo/etendo_copilot_core:${BRANCH_NAME} etendo/etendo_copilot_core:${BRANCH_NAME}-amd64 etendo/etendo_copilot_core:${BRANCH_NAME}-arm64
+        - docker manifest annotate etendo/etendo_copilot_core:${BRANCH_NAME} etendo/etendo_copilot_core:${BRANCH_NAME}-amd64 --os linux --arch amd64
+        - docker manifest annotate etendo/etendo_copilot_core:${BRANCH_NAME} etendo/etendo_copilot_core:${BRANCH_NAME}-arm64 --os linux --arch arm64
+        - docker manifest push etendo/etendo_copilot_core:${BRANCH_NAME}
+      services:
+        - docker
   caches:
     sonar: ~/.sonar
 clone:
@@ -45,66 +105,25 @@ pipelines:
   branches:
     master:
       - step: *build-step
-      - step:
-          image: atlassian/default-image:3
-          name: Deploy to Production
-          deployment: Production
-          script:
-            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-            - IMAGE=etendo/etendo_copilot_core:master
-            - docker build -t ${IMAGE} .
-            - docker push ${IMAGE}
-          services:
-            - docker
-    develop:
-      - step:
-          image: atlassian/default-image:3
-          name: Deploy to Develop
-          deployment: Develop
-          script:
-            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-            - IMAGE=etendo/etendo_copilot_core:develop
-            - docker build -t ${IMAGE} .
-            - docker push ${IMAGE}
-          services:
-            - docker
-    experimental:
       - parallel:
-          - step:
-              name: Build and Push for amd64
-              script:
-                - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-                - IMAGE=etendo/etendo_copilot_core:experimental-amd64
-                - docker build --platform linux/amd64 -t ${IMAGE} .
-                - docker push ${IMAGE}
-              services:
-                - docker
-          - step:
-              name: Build and Push for arm64
-              runs-on:
-                - self.hosted
-                - linux.arm64
-              script:
-                - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-                - IMAGE=etendo/etendo_copilot_core:experimental-arm64
-                - docker build --platform linux/arm64/v8 -t ${IMAGE} .
-                - docker push ${IMAGE}
-              services:
-                - docker
-      - step:
-          name: Create and Push Manifest
-          script:
-            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-            - docker pull etendo/etendo_copilot_core:experimental-amd64
-            - docker pull etendo/etendo_copilot_core:experimental-arm64
-            - docker manifest create etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-amd64 etendo/etendo_copilot_core:experimental-arm64
-            - docker manifest annotate etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-amd64 --os linux --arch amd64
-            - docker manifest annotate etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-arm64 --os linux --arch arm64
-            - docker manifest push etendo/etendo_copilot_core:experimental
-          services:
-            - docker
+          - step: *build-push-amd64
+          - step: *build-push-arm64
+      - step: *create-push-manifest
+    develop:
+      - step: *build-step
+      - parallel:
+          - step: *build-push-amd64
+          - step: *build-push-arm64
+      - step: *create-push-manifest
+    experimental:
+      - step: *build-step
+      - parallel:
+          - step: *build-push-amd64
+          - step: *build-push-arm64
+      - step: *create-push-manifest
   pull-requests:
     "**":
+      - step: *git-police
       - parallel:
           - step: *make-review
           - step: *build-step
