Test dual platform

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -20,21 +20,21 @@ definitions:
         name: Make Review Step
         script:
           - printenv
-          -  echo "-------------------------------------------------------------------------"
-          -  echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-          -  docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:latest
-          -  echo "-------------------------------------------------------------------------"
-          -  sleep 10s
+          - echo "-------------------------------------------------------------------------"
+          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:latest
+          - echo "-------------------------------------------------------------------------"
+          - sleep 10s
           - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
-          -  if [ $response -ne 200 ]; then
-          -    echo "API call failed with status code $response"
-          -    echo "Response text:"
-          -    cat response.txt
-          -    exit 1
-          -  fi
-          -  echo "API call successful with status code $response"
-          -  echo "Response text:"
-          -  cat response.txt
+          - if [ $response -ne 200 ]; then
+          - echo "API call failed with status code $response"
+          - echo "Response text:"
+          - cat response.txt
+          - exit 1
+          - fi
+          - echo "API call successful with status code $response"
+          - echo "Response text:"
+          - cat response.txt
         services:
           - docker
   caches:
@@ -69,18 +69,42 @@ pipelines:
           services:
             - docker
     experimental:
+      - parallel:
+          - step:
+              name: Build and Push for amd64
+              script:
+                - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+                - IMAGE=etendo/etendo_copilot_core:experimental-amd64
+                - docker build --platform linux/amd64 -t ${IMAGE} .
+                - docker push ${IMAGE}
+              services:
+                - docker
+          - step:
+              name: Build and Push for arm64
+              runs-on:
+                - self.hosted
+                - linux.arm64
+              script:
+                - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+                - IMAGE=etendo/etendo_copilot_core:experimental-arm64
+                - docker build --platform linux/arm64/v8 -t ${IMAGE} .
+                - docker push ${IMAGE}
+              services:
+                - docker
       - step:
-          name: Deploy to Experimental
-          deployment: Experimental
+          name: Create and Push Manifest
           script:
             - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
-            - IMAGE=etendo/etendo_copilot_core:experimental
-            - docker build -t ${IMAGE} .
-            - docker push ${IMAGE}
+            - docker pull etendo/etendo_copilot_core:experimental-amd64
+            - docker pull etendo/etendo_copilot_core:experimental-arm64
+            - docker manifest create etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-amd64 etendo/etendo_copilot_core:experimental-arm64
+            - docker manifest annotate etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-amd64 --os linux --arch amd64
+            - docker manifest annotate etendo/etendo_copilot_core:experimental etendo/etendo_copilot_core:experimental-arm64 --os linux --arch arm64
+            - docker manifest push etendo/etendo_copilot_core:experimental
           services:
             - docker
   pull-requests:
-    '**':
+    "**":
       - parallel:
-        - step: *make-review
-        - step: *build-step
+          - step: *make-review
+          - step: *build-step
